### PR TITLE
added lines in test file

### PR DESCRIPTION
**Pull request by jmstechhome25**

### CODE REVIEW

**Review by mahi42511 — COMMENTED** [review]
give me the justification for this line change

**Comment by ukohme** [comment]
Why did you make the changes?

**Comment by jmstechhome25** [comment]
> an

this is our sprint release for login page redirect

**Review by mahi42511 — APPROVED** [review]
Approved

**Review by mahi42511 — APPROVED** [review]
Approve

**Review by ukohme — APPROVED** [review]
Code approved

**Pull request merged**
